version: '3'

services:
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    expose:
      - '6379'
    networks:
      - app-tier
  
  python-news:
    build:
      context: .
      dockerfile: news/Dockerfile
    volumes:
      - .:/app
      - ./common_files:/common_files
    depends_on:
      - redis
    networks:
      - app-tier
    environment:
      - REDDIT_CLIENT_ID=${REDDIT_CLIENT_ID}
      - REDDIT_SECRET=${REDDIT_SECRET}
      - REDDIT_USERNAME=${REDDIT_USERNAME}
      - REDDIT_PASSWORD=${REDDIT_PASSWORD}
  
  python-process:
    build:
      context: .
      dockerfile: process/Dockerfile
    volumes:
      - .:/app
      - ./common_files:/common_files
    depends_on:
      - redis
      - python-news
    networks:
      - app-tier
  
  python-web:
    build:
      context: .
      dockerfile: web/Dockerfile
    volumes:
      - .:/app
      - ./common_files:/common_files
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - python-news
      - python-process
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge